use gitcomet_ui_kit::assets::KitAssets;
use gpui::{AssetSource, Result, SharedString};
use std::borrow::Cow;

// `brand_icon_bytes()`/`BRAND_ICON_ASSETS`, generated by `build.rs` from the
// product artwork in `assets/icons/*.svg`.
include!(concat!(env!("OUT_DIR"), "/icons_assets.rs"));

/// Product artwork paths served alongside the kit's icon set.
const BRAND_ASSETS: [&str; 3] = [
    "gitcomet-window-icon.png",
    "gitcomet-512.png",
    "gitcomet_logo.svg",
];

/// GitComet's artwork (replaceable through the product identity) over the UI
/// kit's icon set, plus any extension assets under `extensions/<id>/`.
#[derive(Default)]
pub struct GitCometAssets {
    extensions: Vec<(SharedString, &'static [u8])>,
}

impl GitCometAssets {
    pub(crate) fn with_extensions(assets: &[(String, &'static [u8])]) -> Self {
        Self {
            extensions: assets
                .iter()
                .map(|(path, bytes)| (SharedString::from(path.clone()), *bytes))
                .collect(),
        }
    }

    fn extension_asset(&self, path: &str) -> Option<Cow<'static, [u8]>> {
        self.extensions
            .iter()
            .find_map(|(asset, bytes)| (asset == path).then_some(Cow::Borrowed(*bytes)))
    }

    fn load_static(path: &str) -> Option<Cow<'static, [u8]>> {
        // A product's own artwork replaces GitComet's under the same names.
        let branding = gitcomet_core::identity::current().branding();
        let branded = match path {
            "gitcomet-window-icon.png" => branding.window_icon_png,
            "gitcomet-512.png" => branding.app_icon_png,
            "gitcomet_logo.svg" => branding.logo_svg,
            _ => None,
        };
        if let Some(bytes) = branded {
            return Some(Cow::Borrowed(bytes));
        }
        match path {
            "gitcomet-window-icon.png" => Some(Cow::Borrowed(include_bytes!(
                "../../../assets/gitcomet-window-icon.png"
            ))),
            "gitcomet-512.png" => Some(Cow::Borrowed(include_bytes!(
                "../../../assets/gitcomet-512.png"
            ))),
            "gitcomet_logo.svg" => Some(Cow::Borrowed(include_bytes!(
                "../../../assets/gitcomet_logo.svg"
            ))),
            other => brand_icon_bytes(other)
                .map(Cow::Borrowed)
                .or_else(|| KitAssets::load_static(other)),
        }
    }

    fn list_static(dir: &str) -> Vec<SharedString> {
        let brand_icons = BRAND_ICON_ASSETS.iter().copied().map(SharedString::from);
        match dir.trim_end_matches('/') {
            // GPUI's AssetRegistry registers only list(""); it does not recurse
            // into directory entries. Include every embedded file here.
            "" => BRAND_ASSETS
                .into_iter()
                .map(SharedString::from)
                .chain(brand_icons)
                .chain(KitAssets::list_static(""))
                .collect(),
            "icons" => brand_icons.chain(KitAssets::list_static("icons")).collect(),
            other => KitAssets::list_static(other),
        }
    }
}

impl AssetSource for GitCometAssets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        if path.starts_with("extensions/") {
            return Ok(self.extension_asset(path));
        }
        Ok(Self::load_static(path))
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        let mut listed = Self::list_static(path);
        let dir = path.trim_end_matches('/');
        if dir.is_empty() || dir == "extensions" || dir.starts_with("extensions/") {
            listed.extend(
                self.extensions
                    .iter()
                    .filter(|(asset, _)| dir.is_empty() || asset.starts_with(&format!("{dir}/")))
                    .map(|(asset, _)| asset.clone()),
            );
        }
        Ok(listed)
    }
}

#[cfg(test)]
mod tests {
    use super::{BRAND_ASSETS, BRAND_ICON_ASSETS, GitCometAssets};
    use gpui::{AssetRegistry, AssetSource, DevicePixels, SvgRenderer, SvgSize, size};
    use std::{collections::BTreeSet, path::Path, sync::Arc};

    fn expected_asset_paths() -> impl Iterator<Item = &'static str> {
        BRAND_ASSETS
            .into_iter()
            .chain(BRAND_ICON_ASSETS.iter().copied())
            .chain(gitcomet_ui_kit::assets::icon_paths())
    }

    #[test]
    fn root_listing_contains_every_asset_once() {
        let listed = GitCometAssets::default()
            .list("")
            .expect("list root assets");
        let paths: BTreeSet<&str> = listed.iter().map(|path| path.as_ref()).collect();

        assert_eq!(paths.len(), listed.len(), "duplicate root asset paths");
        assert_eq!(
            paths,
            expected_asset_paths().collect(),
            "root listing must contain every file without directory placeholders"
        );
    }

    #[test]
    fn gpui_registry_preserves_every_asset() {
        // Exercise the same conversion as Application::with_assets. Checking
        // GitCometAssets::load alone misses paths omitted from the root listing.
        let registry = AssetRegistry::from(GitCometAssets::default());
        for path in expected_asset_paths() {
            let expected = GitCometAssets::default()
                .load(path)
                .expect("load embedded asset")
                .unwrap_or_else(|| panic!("missing embedded asset: {path}"));
            let actual = registry
                .load(path)
                .unwrap_or_else(|| panic!("GPUI registry cannot load {path}"));
            assert!(!actual.is_empty(), "empty asset: {path}");
            assert_eq!(actual, expected, "GPUI changed asset bytes: {path}");
        }
        for path in ["icons", "icons/file_icons", "icons/does-not-exist.svg"] {
            assert!(registry.load(path).is_none(), "unexpected asset: {path}");
        }
    }

    #[test]
    fn registered_svgs_render_visible_pixels() {
        let registry = Arc::new(AssetRegistry::from(GitCometAssets::default()));
        let renderer = SvgRenderer::new(Arc::clone(&registry));
        for path in expected_asset_paths().filter(|path| path.ends_with(".svg")) {
            let bytes = registry
                .load(path)
                .unwrap_or_else(|| panic!("GPUI registry cannot load {path}"));
            let parsed = renderer
                .parse_svg(&bytes)
                .unwrap_or_else(|err| panic!("cannot parse {path}: {err}"));
            for edge in [16, 32] {
                let dimensions = size(DevicePixels(edge), DevicePixels(edge));
                let image = renderer
                    .render_parsed(&parsed, SvgSize::ExactSize(dimensions))
                    .unwrap_or_else(|err| panic!("cannot render {path} at {edge}px: {err}"));
                assert_eq!(image.size(0), dimensions, "incorrect size: {path}");
                let pixels = image.as_bytes(0).expect("rendered SVG frame");
                assert!(
                    pixels.chunks_exact(4).any(|pixel| pixel[3] != 0),
                    "{path} renders blank at {edge}px"
                );
            }
        }
    }

    #[test]
    fn icon_listing_is_the_brand_artwork_over_the_kit_icon_set() {
        let brand_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/icons");
        let brand_on_disk: BTreeSet<String> = std::fs::read_dir(&brand_dir)
            .expect("brand icon directory")
            .map(|entry| {
                format!(
                    "icons/{}",
                    entry.expect("entry").file_name().to_string_lossy()
                )
            })
            .collect();
        let brand_registered: BTreeSet<String> = BRAND_ICON_ASSETS
            .iter()
            .map(|path| path.to_string())
            .collect();
        assert_eq!(brand_registered, brand_on_disk);

        let listed: BTreeSet<String> = GitCometAssets::list_static("icons")
            .into_iter()
            .map(|path| path.to_string())
            .collect();
        let kit: BTreeSet<String> = gitcomet_ui_kit::assets::KitAssets::list_static("icons")
            .into_iter()
            .map(|path| path.to_string())
            .collect();
        assert_eq!(listed, &brand_registered | &kit);
        for icon in listed.iter().filter(|icon| *icon != "icons/file_icons") {
            assert!(GitCometAssets::load_static(icon).is_some(), "{icon}");
        }
    }
}
