family_cases!(architecture, "Web", "WebUpdated");
family_cases!(block, "A", "A2");
family_cases!(c4, "Admin", "AdminUpdated");
family_cases!(class, "Animal", "AnimalUpdated");
family_cases!(er, "CUSTOMER", "CUSTOMERUpdated");
family_cases!(flowchart, "Start", "StartUpdated");
family_cases!(gantt, "Task A", "Task AUpdated");
family_cases!(gitgraph, "F1", "F1Updated");
family_cases!(journey, "Step one", "Step oneUpdated");
family_cases!(kanban, "Task 1", "Task 1Updated");
family_cases!(mindmap, "Root", "RootUpdated");
family_cases!(packet, "Type", "TypeUpdated");
family_cases!(pie, "Dogs", "DogsUpdated");
family_cases!(quadrant, "Sample", "SampleUpdated");
family_cases!(radar, "Alpha", "AlphaUpdated");
family_cases!(requirement, "Login", "LoginUpdated");
family_cases!(sankey, "A", "A2");
family_cases!(sequence, "Hello Bob", "Hello BobUpdated");
family_cases!(state, "Idle", "IdleUpdated");
family_cases!(timeline, "History", "HistoryUpdated");
family_cases!(treemap, "Root", "RootUpdated");
family_cases!(xychart, "Q1", "Q1Updated");
family_cases!(zenuml, "Hello", "HelloUpdated");
